let a = {
  id: 61518815,
  board_id: 3184073381,
  name: 'Form',
  scope: null,
  configuration: {
    app_feature_id: null,
    settings: {
      columns: {
        name: { visible: false, question: 'Name', type: 'name' },
        status: { visible: true, question: 'Status', type: 'color' },
        date4: { visible: true, question: 'Date', type: 'date' },
        pulse__update: { visible: false, question: 'Update' },
        status5: {
          visible: true,
          question: 'how are you?',
          description: 'hello',
          mandatory: false,
          conditionalRules: [],
          question_include_conditional: false,
        },
        multi_select: {
          visible: true,
          type: 'dropdown',
          question: 'Multi select',
        },
        short_text: { visible: true, type: 'text', question: 'Short text' },
        long_text: { visible: true, type: 'long-text', question: 'Long text' },
        number: { visible: true, type: 'numeric', question: 'Number' },
        phone: { visible: true, type: 'phone', question: 'Phone' },
        email: { visible: true, type: 'email', question: 'Email' },
        single_select: {
          visible: true,
          type: 'color',
          question: 'Single select',
        },
        multi_select1: {
          visible: true,
          type: 'dropdown',
          question: 'Multi select',
        },
        true___false: {
          visible: true,
          type: 'boolean',
          question: 'True / False',
        },
        upload_file: { visible: true, type: 'file', question: 'Upload file' },
        date: { visible: true, type: 'date', question: 'Date' },
        date_range: {
          visible: true,
          type: 'timerange',
          question: 'Date range',
        },
        location: { visible: true, type: 'location', question: 'Location' },
        country: { visible: true, type: 'country', question: 'Country' },
      },
      formTitle: 'New Form',
      show_name_question: false,
      createdBy: 33681307,
      sortedQuestionsList: [
        'name',
        'short_text',
        'long_text',
        'number',
        'phone',
        'email',
        'single_select',
        'multi_select1',
        'true___false',
        'upload_file',
        'date',
        'date_range',
        'location',
        'country',
        'pulse__update',
      ],
      conditionalRules: {},
    },
  },
  type: 'FormBoardView',
  created_by: 33681307,
  created_at: '2022-09-04T06:25:21Z',
  pos: 0.0,
  view_specific_data: {
    token: 'ec8286c3e78504924b0c7c7bae8e6a40',
    disabled: false,
  },
  app_feature_id: null,
  client_instance_token: null,
  is_default: false,
};
